### ISSUE TITLE
Failure with message `Create submission failed, status code Conflict, reason phrase Conflict`

### ISSUE THREAD

**Issue by yaakovschectman** [microsoft/store-submission#14]
I am attempting to test this action. The step in the workflow file is as follows:

        uses: isaacrlevin/windows-store-action@1.0
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_ClIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          app-id: ${{ secrets.STORE_APP_ID }}
          package-path: ${{ github.workspace }}\build\windows\runner\Release

When attempting to run it, this step fails with the error message in the title. I have tried changing some of the secret values to random incorrect values to see if the error message changes, and indeed, for each change I have tried, inputting the wrong value gives a different and more clear error message telling me what the problem was, but when all values are correct (as far as I am aware), I receive the title message, whose meaning I am unsure of.

What does this error mean, and what might be the root cause?

**Comment by azchohfi** [comment]
Hello @yaakovschectman.
It seems like you are publishing an MSIX, not an MSI, so you are using https://github.com/isaacrlevin/windows-store-action, and not this package.

Still, I believe I can help you.

This seems similar to this issue:
https://github.com/isaacrlevin/windows-store-action/issues/5

Which basically means that you have a pending submission. If you always submit using the APIs, you can simply go to Partner Center and delete that pending submission (pretty much deleting the draft). The problem is that the APIs do not allow us to delete a submission that was created in the portal. API calls can only delete submissions created by other API calls.

I hope that helps!

**Comment by yaakovschectman** [comment]
@azchohfi Thank you for your help.  
Would you know anything about [this issue](https://github.com/isaacrlevin/windows-store-action/issues/8)? It does not appear that anyone has responded to it yet.

**Comment by azchohfi** [comment]
I'll reply there.
